#
# WikiCMS graph schema
#
#  WF 2024-10-22
#
node_id_type_name: str

node_type_configs:

  Server:
    label: Server
    icon: cloud
    key_field: alias
    dataclass_name: backend.server.Server
    viewclass_name: frontend.servers_view.ServerView
    display_order: 10
    display_name: Server
    description: HTML Webserver hosting Services e.g. Wikis



